http_server:
  api_version: "v1"
  port: 8045
  read_timeout_sec: 30
  write_timeout_sec: 30
  shutdown_timeout_sec: 10

tcp_server:
  port: 10010

database:
  username: "forum"
  password: "forum"
  name: "forum"
  host: "localhost"
  port: 6789

redis:
  password: "forum"
  host: "localhost"
  port: 9999
  database: 0

cloudinary:
  cloud_name: "duppvsny0"
  api_key: "453378772488287"
  api_secret: "POkU1uLE5zEchkpf9MvrjimdWm4"
  upload_folder: "forum_app"

mail:
  smtp_host: "smtp.gmail.com"
  smtp_port: 587
  smtp_username: "nguyenle.workspace@gmail.com"
  smtp_password: "cwpa uyfq dlzn iymi"
  validate_mail_pattern_dir: "./asset/validate_pattern.html"

log:
  log_level: "info"
  file_pattern: "2006-01-02"
  max_size: 10
  base_log_dir: "logs"